[package]
name = "spl-store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
no-entrypoint = []

[dependencies]
borsh = "0.10.3"
borsh-derive = "0.10.3"
dotenv = "0.15.0"
spl-associated-token-account = { version = "2.2.0", features = ["no-entrypoint"] }
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
thiserror = "1.0.50"

[dev-dependencies]
eyre = "0.6.8"
solana-program-test = "1.17.4"
solana-sdk = "1.17.4"

[lib]
name = "spl_store"
crate-type = ["cdylib", "lib"]